language: dart
sudo: required
dist: xenial
dart:
  - stable
  - beta
  - dev
before_script:
  - cd repo_support
  - dart pub get
  - dart pub run chrome_travis:init
  - source $(dart pub run chrome_travis:env_rc)
script:
  - dart run tool/travis.dart
matrix:
  allow_failures:
    - dart: dev