# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:pedantic/analysis_options.yaml

analyzer:
  # strong-mode:
    #implicit-casts: false
    # implicit-dynamic: false

linter:
  rules:
    - avoid_dynamic_calls
    - avoid_empty_else
    - avoid_slow_async_io
    - camel_case_types
    - cancel_subscriptions
    - constant_identifier_names
    - control_flow_in_finally
    - directives_ordering
    - empty_statements
    - hash_and_equals
    - implementation_imports
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - no_adjacent_strings_in_list
    - non_constant_identifier_names
    - overridden_fields
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - prefer_const_constructors
    - prefer_initializing_formals
    - prefer_typing_uninitialized_variables
    - prefer_void_to_null
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_null_aware_assignments
    - unnecessary_statements
    # === doc rules ===
    - public_member_api_docs
