name: synchronized
description: Lock mechanism to prevent concurrent access to asynchronous code.
version: 3.0.0-nullsafety.1
homepage: https://github.com/tekartik/synchronized.dart/tree/master/synchronized

environment:
  sdk: '>=2.12.0-29 <3.0.0'

dev_dependencies:
  pedantic: '>=1.10.0-nullsafety.3 <3.0.0'
  pub_semver: '>=1.4.4'
  test: '>=1.16.0-nullsafety'
  build_runner: '>=1.10.2'
  build_test: '>=1.2.1'
  build_web_compilers: '>=1.1.0'
  process_run: '>=0.10.12+3'
  io: '>=0.3.4'
  yaml: '>=2.2.1'

